### ISSUE TITLE
The LeetCode link in the README is broken.

### ISSUE THREAD

**Issue by Anuj-Kundar** [Deepakvrma14/Deepakvrma14#1]

**Comment by Deepakvrma14** [comment]
hii thanyou so much for the issue, i guess it's working as i have seen but you may share a ss suggesting where you feel there is an issue , from my end evrything is working

**Comment by Anuj-Kundar** [comment]
when i click on leetcode icon under *connect with me* section it shows me server error 404:
![image](https://github.com/Deepakvrma14/Deepakvrma14/assets/89484481/c57342e4-5aae-46cd-a59e-a562addce3c9)

**Comment by Deepakvrma14** [comment]
> when i click on leetcode icon under _connect with me_ section it shows me server error 404: ![image](https://private-user-images.githubusercontent.com/89484481/289360826-c57342e4-5aae-46cd-a59e-a562addce3c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzk4MzAsIm5iZiI6MTcwMjIzOTUzMCwicGF0aCI6Ii84OTQ4NDQ4MS8yODkzNjA4MjYtYzU3MzQyZTQtNWFhZS00NmNkLWE1OWUtYTU2MmFkZGNlM2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDIwMTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMzAyNTVjZTIyYjUyNGI3MTVkMWMzNjNiMmNjNWE5YzY4NjcxMzRjZjY5M2ZkZGZhMGQ2NjA4Yjk5YTUwMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FPrU4BdpqsXyFGV7wCnrZOQiXtDF2CWeQSz1h2NJS0c)

got it, thankyou so much for the issue, had fixed it now you can recheck, thankyou again
